const en = {
  twitter: {
    alt_found: {
      s: '<== We found a possible description for this image and copied it to the clipboard.<br> Please click the "{value}" button to add it.',
      p: '<== We found possible descriptions for these images<br> Please click the "{value}" button to add them.',
    },
    alert_message:
      '<== Try to add a description<br> by clicking the "{value}" button.',
    cycle_arrows:
      "Click the arrows buttons below to add the descriptions to the other images.",
    save_button:
      '<== Don\'t forget to apply the changes by clicking the "{value}" button.',
    paste_message:
      "<== Paste here the description<br> and then edit it to be as correct as possible.",
    alts_list_message:
      "We found potential descriptions for this image.\n Copy and paste the descriptions that best fit the image\n and then edit it to be as accurate as possible.",
  },
  facebook: {
    alt_found: {
      s: 'We found a possible description for this image.<br> Please click the "{value}" button to add it. ==>',
      p: 'We found possible descriptions for these images<br> Please click the "{value}" button to add them. ==>',
    },
    alert_message:
      'Try to add a description by clicking the "{value}" button. ==>',
    save_button:
      'Don\'t forget to apply the changes by clicking the "{value}" button above.',
    paste_message:
      "<== Paste here the description<br> and then edit it to be as correct as possible.",
    description_tab: '<== Click the "{value}" button to add a description.',
    conclude_button: 'Click the "{value}" button above to conclude the post.',
    hover_image: 'Hover the image,<br>then click the "Edit" button. ==>',
  },
  insert_alts_description: "Other possible descriptions are:",
  description: {
    text: "This image may contain ",
    concepts: "The image may contain these concepts: ",
    watermark: "*Description generated by SONAAR.",
    nothing: "No additional descriptions",
  },
};
